# Generated by Django 2.2.5 on 2019-10-03 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_site', '0004_blog_post_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='post_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
